#!/bin/sh
# Utilizado para corrigir erro de permissão apontado no laravel no storage

sudo chown -R $USER: *
sudo chown -R www-data: bootstrap/cache
sudo find storage -type d -exec chmod -R 775 {} \;
sudo find bootstrap/cache -type d -exec chmod -R 775 {} \;

sudo chmod -R ug+rwX ./storage ./bootstrap/cache
